--Creacion de USUARIOS
CREATE USER BD_PEDIDOS IDENTIFIED BY 123
    DEFAULT TABLESPACE Users
    TEMPORARY TABLESPACE temp
    QUOTA UNLIMITED ON Users;
    
--Asignar PRIVILEGIOS > Se le asignara al ROL
CREATE ROLE ADMINISTRADORES;

GRANT CREATE SESSION, CREATE ANY TABLE, 
CREATE ANY PROCEDURE, ALTER ANY TABLE,
ALTER ANY PROCEDURE, DROP ANY TABLE, DROP
ANY PROCEDURE TO ADMINISTRADORES;

GRANT ADMINISTRADORES TO BD_PEDIDOS;

GRANT SELECT ON BD_PEDIDOS.ORDENES TO ADMINISTRADORES

GRANT CREATE ANY TRIGGER, ALTER ANY TRIGGER, DROP  ANY TRIGGER TO ADMINISTRADORES;